drop table if exists post CASCADE;
drop table if exists post_comment CASCADE;
drop table if exists post_tag CASCADE;
drop table if exists tag CASCADE;

create table post (
    post_id bigint generated by default as identity,
    title varchar(255),
    primary key (post_id)
);

create table post_comment (
    post_comment_id bigint generated by default as identity,
    review varchar(255),
    post_id bigint,
    primary key (post_comment_id)
);

create table post_tag (
    post_id bigint not null,
    tag_id bigint not null
);

create table tag (
    tag_id bigint generated by default as identity,
    name varchar(255),
    primary key (tag_id)
);

alter table post_comment 
add constraint FKna4y825fdc5hw8aow65ijexm0 
foreign key (post_id) 
references post;

alter table post_tag 
add constraint FKac1wdchd2pnur3fl225obmlg0 
foreign key (tag_id) 
references tag;

alter table post_tag 
add constraint FKc2auetuvsec0k566l0eyvr9cs 
foreign key (post_id) 
references post;


CREATE VIEW vw_post
AS
SELECT 
--UUID() AS ID, --String
ROWNUM() AS ID,
p.POST_ID,
p.TITLE,
pc.REVIEW,
t.NAME
FROM POST p
LEFT JOIN POST_COMMENT pc on pc.POST_ID = p.POST_ID
LEFT JOIN POST_TAG pt on pt.POST_ID = p.POST_ID
LEFT JOIN TAG t on t.TAG_ID = pt.TAG_ID;